services:
  db:
    image: postgres:16
    container_name: my-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankApp
      POSTGRES_USER: ${SPRING_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: